DataDog/dd-sdk-roku

- dist/components/logs/LogsAgent.brs
- library/components/logs/LogsAgent.bs
Add some visibility in the telnet console by forwarding logs sent to DD to the standard outptu
> RUMM-2763 forward logs to console

- .gitattributes
- dist/components/rum/RumAgent.brs
- dist/components/rum/RumAgent.xml
- dist/components/rum/RumApplicationScope.brs
- dist/components/rum/RumApplicationScope.xml
- dist/components/rum/RumSessionScope.brs
- dist/components/rum/RumSessionScope.xml
- dist/source/wrapper/DdUrlTransfer.brs
- library/components/rum/RumAgent.bs
- library/components/rum/RumAgent.xml
- library/components/rum/RumApplicationScope.bs
- library/components/rum/RumApplicationScope.xml
- library/components/rum/RumSessionScope.bs
- library/components/rum/RumSessionScope.xml
- library/source/wrapper/DdUrlTransfer.bs
- test/source/asserts/Asserts.bs
- test/source/tests/rum/Test__RumSessionScope.bs
Let customer define a Session Sampling rate, similar to what we have in other SDKs
> RUMM-2762 Add session sampling

- README.md
- sample/components/MainScene.bs
- sample/components/screens/DebugScreen.bs
- sample/components/screens/DebugScreen.xml
- sample/components/screens/NetworkScreen.bs
- sample/components/screens/VideoScreen.xml
- sample/source/main.bs
This PR updates the sample app with an option to crash the channel, to test the crash reporting feature (cf #43)
> RUMM-2487 add crash in sample app

- dist/source/datadogSdk.brs
- library/source/datadogSdk.bs
- test/source/tests/Test__datadog.bs
Adds support to our AP1 datacenter, and use subdomain-less endpoints
> RUMM-2890 Add support to AP1 datacenter

- dist/components/logs/LogsAgent.brs
- dist/components/logs/LogsAgent.xml
- dist/components/rum/RumActionScope.brs
- dist/components/rum/RumAgent.brs
- dist/components/rum/RumAgent.xml
- dist/components/rum/RumApplicationScope.brs
- dist/components/rum/RumApplicationScope.xml
- dist/components/rum/RumViewScope.brs
- dist/source/datadogSdk.brs
- library/components/logs/LogsAgent.bs
- library/components/logs/LogsAgent.xml
- library/components/rum/RumActionScope.bs
- library/components/rum/RumAgent.bs
- library/components/rum/RumAgent.xml
- library/components/rum/RumApplicationScope.bs
- library/components/rum/RumApplicationScope.xml
- library/components/rum/RumViewScope.bs
- library/source/datadogSdk.bs
- test/source/tests/logs/Test__LogsAgent.bs
- test/source/tests/rum/Test__RumActionScope.bs
- test/source/tests/rum/Test__RumAgent.bs
- test/source/tests/rum/Test__RumApplicationScope.bs
- test/source/tests/rum/Test__RumViewScope.bs
Ensure the SDK reports the device model and display name, and the os version number properly as the user agent not always report all those info.
> RUMM-3036 send device info

- dist/components/core/MultiTrackUploaderTask.brs
- dist/components/core/WriterTask.brs
- library/components/core/MultiTrackUploaderTask.bs
- library/components/core/WriterTask.bs
- sample/components/screens/DebugScreen.bs
- tools/roku/install.sh
The batching mecanism was broken when we introduced the last known view event file.
This PR fixes this by excluding it from possible file to append a new event to.
> RUMM-3067 fix batching mecanism

- README.md
- dist/source/datadogSdk.brs
- dist/source/wrapper/DdUrlTransfer.brs
- library/source/datadogSdk.bs
- library/source/wrapper/DdUrlTransfer.bs
- sample/components/MainScene.bs
- sample/components/screens/HomeScreen.bs
- sample/components/screens/HomeScreen.xml
- sample/credentials.json.template
- sample/source/main.bs
Changes the way the SDK is initialised, so that it can be set up from the `main.brs` file of a channel
Making the onboarding and setup easier
> RUMM-3019 init SDK from main

- dist/components/rum/RumCrashReporterTask.brs
- library/components/rum/RumCrashReporterTask.bs
- test/source/asserts/Asserts.bs
- test/source/tests/Test__fileUtils.bs
- test/source/tests/core/Test__MultitrackUploaderTask.bs
- test/source/tests/rum/Test__RumCrashReporterTask.bs
- test/source/tests/rum/Test__RumViewScope.bs
There was an instance in which the last known view event was missing the expected attributes. We're still not sure where the root cause is, but we added a test to ensure the main necessary attributes are present before using them
> RUMM-3042 prevent crashing host channel when reporting exit reason

- dist/components/core/WriterTask.brs
- library/components/core/WriterTask.bs
- sample/source/main.bs
- test/components/TestRunner.bs
- test/source/testFramework/TFUtils.brs
- test/source/tests/core/Test__WriterTask.bs
Fixes the logic to detect writeable file and avoid appending data to the last known view file
> RUMM-3019 fix writeable file logic

- package.json
- tools/repo/release.sh
Updates the package.json for the first release and the release script
> RUMM-3010 update package.json and release script

- dist/source/wrapper/DdUrlTransfer.brs
- library/source/wrapper/DdUrlTransfer.bs
- sample/components/screens/NetworkScreen.bs
- test/source/tests/Test__fileUtils.bs
- test/source/tests/rum/Test__RumCrashReporterTask.bs
- test/source/tests/rum/Test__RumViewScope.bs
Cleans up some typo and unused variables in the test/sample code
> Cleanup typo and dead code

- dist/source/wrapper/DdUrlTransfer.brs
- library/source/wrapper/DdUrlTransfer.bs
- sample/components/screens/NetworkScreen.bs
- sample/components/tasks/NetworkTestTask.bs
- sample/credentials.json.template
- sample/source/main.bs
- test/components/TestRunner.bs
- test/source/mock/Mock.bs
- test/source/tests/Test__DdUrlTransfer.bs
Add an option to set a list of traced hosts in the `DdUrlTransfer`  component
> RUMM-2809 traced hosts

- .gitlab-ci.yml
- Dockerfile.gitlab
- README.md
- dist/source/datadogSdk.brs
- dist/source/internalLogger.brs
- dist/source/wrapper/DdUrlTransfer.brs
- library/package.json
- library/source/datadogSdk.bs
- library/source/wrapper/DdUrlTransfer.bs
- sample/components/screens/NetworkScreen.xml
- sample/components/tasks/NetworkTestTask.bs
- sample/credentials.json.template
- sample/package.json
- sample/source/main.bs
- test/package.json
- test/source/testFramework/ItemGenerator.brs
- test/source/tests/Test__DdUrlTransfer.bs
- test/source/tests/rum/Test__RumAgent.bs
- test/source/tests/rum/Test__RumSessionScope.bs
Adds OTel support and let user chose their tracing header per host.
> RUM-462 / RUM-1964 add OTel support

- dist/components/rum/RumActionScope.brs
- dist/components/rum/RumActionScope.xml
- dist/components/rum/RumAgent.brs
- dist/components/rum/RumSessionScope.brs
- dist/components/rum/RumViewScope.brs
- dist/components/rum/RumViewScope.xml
- dist/source/rum/rumHelper.brs
- dist/source/rum/rumRawEvents.brs
- library/components/rum/RumActionScope.bs
- library/components/rum/RumActionScope.xml
- library/components/rum/RumAgent.bs
- library/components/rum/RumSessionScope.bs
- library/components/rum/RumViewScope.bs
- library/components/rum/RumViewScope.xml
- library/source/rum/rumHelper.bs
- library/source/rum/rumRawEvents.bs
- sample/components/screens/DebugScreen.bs
- sample/components/tasks/RequestTask.bs
- test/source/mock/Mock.bs
- test/source/tests/rum/Test__RumActionScope.bs
- test/source/tests/rum/Test__RumAgent.bs
- test/source/tests/rum/Test__RumSessionScope.bs
- test/source/tests/rum/Test__RumViewScope.bs
- tools/roku/install.sh
Adds an optional argument to the `RumAgent` component to allow customers to pass custom attributes for individual events.
> RUM-2351 Allow custom context per event

- test/components/TestRunner.bs
- test/components/TestScreen.bs
- test/source/testFramework/Logger.brs
- test/source/testFramework/TestRunner.brs
- test/source/tests/Test__timeUtils.bs
- test/source/tests/core/Test__WriterTask.bs
- test/source/tests/rum/Test__RumSessionScope.bs
Improve the unit test suite
- Show the tests in progress (allows having info early and not wait for the full suite to run)
- Update time utils (unfortunately has to use hardcoded values)
- Fix some flaky tests
> Update Unit tests

- dist/components/core/MultiTrackUploaderTask.brs
- library/components/core/MultiTrackUploaderTask.bs
- test/source/tests/core/Test__MultitrackUploaderTask.bs
Take into account additional Server errors which could happen and unify behavior with other RUM SDKs
> RUM-2750 take into account new server errors

- dist/components/rum/RumAgent.brs
- dist/components/rum/RumCrashReporterTask.brs
- dist/components/rum/RumCrashReporterTask.xml
- library/components/rum/RumAgent.bs
- library/components/rum/RumCrashReporterTask.bs
- library/components/rum/RumCrashReporterTask.xml
- sample/components/screens/DebugScreen.bs
- sample/source/main.bs
- test/source/tests/rum/Test__RumCrashReporterTask.bs
Add support for Roku 13.0 new information about crashes.
> RUM-3413 Read console log for crash report on Roku 13+

- README.md
Improve documentation around manual instrumentation
> Improve doc on custom context

- .gitignore
- CONTRIBUTING.md
* Ignoring `sample/credentials.json` so we can always have local `credentials.json` for sampe app
* Add `telnet` installation in "Setup your developer Environment"
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)
> Update .gitignore and CONTRIBUTING.md

- dist/source/wrapper/DdUrlTransfer.brs
- library/source/wrapper/DdUrlTransfer.bs
- test/source/tests/Test__DdUrlTransfer.bs
Add baggage with session id in trace headers.
example:
```
baggage: session.id=xxxx;
```
RUM-9705
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)
> RUM-9705: Add baggage with session id in trace headers

- CHANGELOG.md
- dist/source/datadogSdk.brs
- library/package.json
- library/source/datadogSdk.bs
- package.json
- sample/package.json
- test/package.json
Bump version to 1.2.0
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)
> Bump version to 1.2.0
